[package]
name = "test-whisper-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
whisper-rs = { version = "0.10.0", features = [] }
whisper-rs-sys = "0.8.0"
